# Generated by Django 4.2.25 on 2025-10-17 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Underlying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('last_price', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateField()),
                ('strike', models.FloatField()),
                ('option_type', models.CharField(choices=[('CALL', 'CALL'), ('PUT', 'PUT')], max_length=4)),
                ('implied_vol', models.FloatField()),
                ('last_price', models.FloatField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('underlying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.underlying')),
            ],
        ),
    ]
